version: '3.3'
services:
  ws:
    restart: always
    env_file:
      - ./.env
    build:
      context: ./
    networks:
      - ws
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./config:/app/config 
    links:
      - postgres
    environment:
      - RUNNING_ENV=docker

  postgres:
    image: postgres:latest
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
    networks:
      - ws
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}

networks:
  ws:
